name: artifact
on:
  workflow_dispatch:
jobs:
 jobs1:
  runs-on: ubuntu-latest
  steps:
  - uses: actions/checkout@v1
  - run: |	
      mkdir -p ~/new/artifact
      echo hello > ~/new/artifact/world.txt
  - uses: actions/upload-artifact@v2
    with:	
      name: 'Artifacts-V2'	
      path: '~/new/**/*'


