name: call-epg-grabbers
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: '**'
    types: [closed]
  schedule:
  - cron: '30 1 */5 * *'
jobs:
    strategy:
      max-parallel: 4
      matrix:
        include:
           - path: /.github/workflows/epg-grabber-1.yml
             script: m.tv.sms.cz.config.js
           - path: ./.github/workflows/epg-grabber-2.yml
             script: horizon.tv.config.js
           - path: ./.github/workflows/epg-grabber-3.yml
             script: o2tv.cz.config.js

     steps:
      - uses: ${{ matrix.path }}