name: call-epg-grabbers
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
  schedule:
  - cron: '30 1 */5 * *'
jobs:
  grab1:
    uses: ./.github/workflows/epg-grabber-1.yml
    secrets: inherit
  grab2:
    uses: ./.github/workflows/epg-grabber-2.yml
    secrets: inherit
  grab3:
    uses: ./.github/workflows/epg-grabber-3.yml
    secrets: inherit
