name: call-epg-grabbers
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
  schedule:
  - cron: '30 1 */5 * *'
jobs:
  grab1:
    uses: ./.github/workflows/epg-grabber-1.yml
    secrets: inherit
  grab2:
    uses: ./.github/workflows/epg-grabber-2.yml
    secrets: inherit
  grab3:
    uses: ./.github/workflows/epg-grabber-3.yml
    secrets: inherit


  push:
    runs-on: ubuntu-latest
    needs: [grab1,grab2,grab3]
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: timestamp
        id: timestamp
        run: |
          date >> ./timestamp
          stamp=$(date -r ./timestamp)
          echo $stamp
          cd ${{ github.workspace }}
          sed -i "12s/.*/$stamp | epg-grabber/" ./README.md
        shell: bash

      - name: Tree
        run: |
         echo ***./***
         tree -h -L 2 ./

      - name: outputs_grabers
        run: |
         echo "outputs outcome"
         echo ${{ needs.grab1.outputs.grab1_outcome }}
         echo ${{ needs.grab2.outputs.grab2_outcome }}
         echo ${{ needs.grab3.outputs.grab3_outcome }}
         echo "grabs outcome"
         echo ${{ needs.grab1.outcome }}
         echo ${{ needs.grab2.outcome }}
         echo ${{ needs.grab3.outcome }}


      - name: GITHUB_STEP_SUMMARY
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**grabers** | **sumary**" >> $GITHUB_STEP_SUMMARY
          echo "---: | :--- " >> $GITHUB_STEP_SUMMARY
          echo "grab1 | $(echo ${{ needs.grab1.outputs.grab1_outcome }})" >> $GITHUB_STEP_SUMMARY
          echo "grab2 | $(echo ${{ needs.grab2.outputs.grab2_outcome }})" >> $GITHUB_STEP_SUMMARY
          echo "grab3 | $(echo ${{ needs.grab3.outputs.grab3_outcome }})" >> $GITHUB_STEP_SUMMARY

      # git add ...guide.xml
      - name: Update
        id: update
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase false
          git add ./README.md
          git commit -m "epg-grabber"
          git pull
          git push