name: call-epg-grabbers
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: '**'
    types: [closed]
  schedule:
  - cron: '30 1 */5 * *'
jobs:
  m.tv.sms.cz.config.js:
    uses: ./.github/workflows/epg-grabber-2.yml
  horizon.tv.config.js:
    uses: ./.github/workflows/epg-grabber-2.yml
  o2tv.cz.config.js:
    uses: ./.github/workflows/epg-grabber-2.yml
