name: call-epg-grabbers
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: '**'
    types: [closed]
  schedule:
  - cron: '30 1 */5 * *'
jobs:
  grab1:
    uses: ./.github/workflows/epg-grabber-1.yml
    secrets: inherit
    
    name: Deploy
     run:|
      git config --global user.email ${{ secrets.EMAIL }}
      git config --global user.name ${{ secrets.NAME }}
      git pull
      git add ${{ github.workspace }}/README.md
      git add ./*.csv
      git add ./*.xml
      git commit -m "epg-grabber"
      git push
