name: call-epg-grabbers
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
  schedule:
  - cron: '30 1 */5 * *'
jobs:
  grab1:
    uses: ./.github/workflows/epg-grabber-1.yml
    secrets: inherit
  grab2:
    uses: ./.github/workflows/epg-grabber-2.yml
    secrets: inherit
  grab3:
    uses: ./.github/workflows/epg-grabber-3.yml
    secrets: inherit

  push:
    runs-on: ubuntu-latest
    needs: [grab1,grab2,grab3]
    steps:
      - name: timestamp
        id: timestamp
        run: |
          date >> ./timestamp
          stamp=$(date -r ./timestamp)
          echo $stamp
          cd ${{ github.workspace }}
          sed -i "12s/.*/$stamp | epg-grabber/" ./README.md
        shell: bash

      - name: Update
        id: update
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git add ${{ github.workspace }}/README.md
          git commit -m "epg-grabber"
          git push