name: db-ip
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 3 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./db-ip    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: chmod
        run: chmod +x ./asn.sh
        shell: bash
            


      - name: timestamp
        run: |
          date >> ./data/timestamp
          stamp=$(date -r ./data/timestamp)
          echo $stamp
          cd ${{ github.workspace }} 
          sed -i '9s/.*/$stamp "| db-ip"/' ./README.md       
          shell: bash 

      - name: tree 
        run: |
         echo ***./data***
         tree -h ./data        

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ${{ github.workspace }}/README.md             
          git add ./data/*.json    
          git add ./data/{Clear.csv,AsnIsp.csv} 
          git commit -m "db-ip"
          git push

        
          
        
          

   

    


         
          
        
        
