name: db-ip
on:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
  schedule:
  - cron: '0 0 8 */3 *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./db-ip
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: chmod
        run: chmod +x ./asn.sh
        shell: bash

      - name: run sh
        run: bash ./asn.sh
        shell: bash
        
        
      - name: install npm packages
        run: npm install
      - name: gh-merge
        run: npm run gh-merge
      - name: gh-asn
        run: npm run gh-asn
      - name: gh-od-do
        run: npm run gh-od-do
        
      - name: data
        run: |
         jq --compact-output 'group_by(.asn) | map({ "asn": .[0].asn,"isp": map(."isp") | unique, "od-do": map(."od-do") | unique })' ./data/Clear.json > ./data/data.json
        shell: bash

      - name: timestamp
        run: |
          date >> ./data/timestamp
          stamp=$(date -r ./data/timestamp)
          echo $stamp
          cd ${{ github.workspace }}
          sed -i "9s/.*/$stamp | db-ip/" ./README.md
        shell: bash

      - name: tree
        run: |
         echo ***./data***
         tree -h ./data

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ${{ github.workspace }}/README.md
          git add ./data/*.json
          git add ./data/*.csv
          git commit -m "db-ip"
          git push
