name: epg-grabber-1
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    continue-on-error: false
    strategy:

      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    outputs:
      output_grab2: ${{ steps.grab2.outputs.grab2_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NpmInstall
        run: npm install

      - name: Grab
        id: grab1
        run: npm run grab1

      - name: outcome
        id: grab1_outcome
        shell: bash
        run: |
         echo ${{ steps.grab1.outcome }}
         echo "grab1_outcome=${{steps.grab1.outcome }}" >> $GITHUB_OUTPUT

      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase false
          echo ${{ steps.grab2.outcome }}
          git add m.tv.sk.cz.guide.xml
          git commit -m "epg-grabber - ${{ steps.grab2.outcome }}"
          git pull
          git push
