name: epg-grabber-3
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
      outputs:
       grab3_outcome:
        description: "jobs.grab.outputs.output_grab3"
        value: ${{ jobs.grab.outputs.output_grab3 }}

  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    continue-on-error: true
    strategy:

      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    outputs:
      output_grab3: ${{ steps.grab3_outcome.outputs.grab3_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NpmInstall
        run: npm install

      - name: Grab
        id: grab3
        run: |
          version=$(curl -X HEAD -w "%{http_code}" \
          --no-progress-meter \
          --connect-timeout 20 \
          --max-time 20 \
          --url 'https://api.o2tv.cz/unity/api/v1/epg/depr/?forceLimit=true&limit=1' \
          -I \
          -H 'User-Agent: Mozilla/5.0 (Linux; Android 8.0.0; Nexus 6P Build/OPP3.170518.006) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Mobile Safari/537.36' \
          -H 'Accept: application/json,*/*' \
          -H 'DNT: 1' \
          -H 'Connection: keep-alive' \
          -o /dev/null)
          if [ $version -eq 0 ]
          then
          echo curl OK
          else
          exit
          fi
          npm run grab3

      - name: outcome
        id: grab3_outcome
        shell: bash
        run: |
         echo ${{ steps.grab3.outcome }}
         echo "grab3_outcome=${{ steps.grab3.outcome }}" >> $GITHUB_OUTPUT


      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase true
          echo ${{ steps.grab3.outcome }}
          git add ./guide/o2tv.cz_cz.guide.xml
          git commit -m "epg-grabber - ${{ steps.grab3.outcome }}"
          git pull
          git push -f
