name: epg-grabber-2
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    outputs:
    output_grab2: ${{ steps.grab2.outputs.grab2_ outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NpmInstall
        run: npm install

      - name: Grab
        id: grab2
        run: npm run grab2

      - name: outcome
        id: grab2_outcome
        shell: bash
        run: |
         echo ${{ steps.grab2.outcome }}
         echo "grab2_outcome=${{steps.grab2.outcome }}" >> $GITHUB_OUTPUT

      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase false
          echo ${{ steps.grab2.outcome }}
          git add ./*.csv
          git add ./*.xml
          git commit -m "epg-grabber - ${{ steps.grab2.outcome }}"
          git pull
          git push
