name: epg-grabber-1
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
      outputs:
       grab1_outcome:
        description: "jobs.grab.outputs.output_grab1"
        value: ${{ jobs.grab.outputs.output_grab1 }}

  workflow_dispatch:

# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    strategy:
      fail-fast: false
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    outputs:
      output_grab1: ${{ steps.grab1_outcome.outputs.grab1_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: NpmInstall
        run: npm install

      - name: Grab
        id: grab1
        run: |
         # exit 1
         npm run grab1

      - name: outcome
        id: grab1_outcome
        shell: bash
        run: |
         echo ${{ github.event_name }}
         echo ${{ steps.grab1.outcome }}
         echo "grab1_outcome=${{ steps.grab1.outcome }}" >> $GITHUB_OUTPUT


      - name: Deploy
        if: ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event_name == 'schedule' }}
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase true
          echo ${{ steps.grab1.outcome }}
          git add ./guide/mujtvprogram.cz_cz.guide.xml
          git commit -m "epg-grabber - ${{ steps.grab1.outcome }}"
          git pull
          git push -f
