name: epg-grabber-2
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NpmInstall
        run: npm install

      - name: Grab
        run: npm run grab2


      - name: timestamp
        run: |
          date >> ./timestamp
          stamp=$(date -r ./timestamp)
          echo $stamp
          cd ${{ github.workspace }}
          sed -i "13s/.*/$stamp | epg-grabber/" ./README.md
        shell: bash

      - name: Tree
        run: |
         echo ***./***
         tree -h -L 2 ./
      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase false
          git add ${{ github.workspace }}/README.md
          git add ./*.csv
          git add ./*.xml
          git commit -m "epg-grabber"
          git checkout ${{ github.workspace }}/README.md
          git merge ort
          git push
