name: epg-grabber-3
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    outputs:
      output_grab3: ${{ steps.grab3.outputs.grab3_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NpmInstall
        run: npm install

      - name: Grab
        id: grab3
        run: npm run

      - name: outcome
        id: grab3_outcome
        shell: bash
        run: |
         echo ${{ steps.grab3.outcome }}
         echo "grab3_outcome=${{steps.grab3.outcome }}" >> $GITHUB_OUTPUT


      - name: Deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase false
          echo ${{ steps.grab3.outcome }}
          git add ./*.csv
          git add ./*.xml
          git commit -m "epg-grabber - ${{ steps.grab3.outcome }}"
          git pull
          git push
