name: epg-grabber 
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 3 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber   
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NpmInstall
        run: npm 

      - name: grab
        run: npm run grab


      - name: timestamp
        run: |
          date >> ./timestamp
          stamp=$(date -r ./timestamp)
          echo $stamp
          cd ${{ github.workspace }} 
          sed -i "12s/.*/$stamp | epg-grabber/" ./README.md       
        shell: bash 

      - name: tree 
        run: |
         echo ***./***
         tree -h -L 2 ./        

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ${{ github.workspace }}/README.md             
          git add ./*.csv    
          git add ./*.xml 
          git commit -m "epg-grabber"
          git push

        
          
        
          

   

    


         
          
        
        
