name: epg-grabber-3
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
      outputs:
       grab3_outcome:
        description: "jobs.grab.outputs.output_grab3"
        value: ${{ jobs.grab.outputs.output_grab3 }}

  workflow_dispatch:
  pull_request_target:
    branches: 'main'
    types: [closed]
env:
  env_var3: ${{ vars.CORS_ELEONORA }}
# schedule:
#  - cron: '30 1 */5 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 480
    continue-on-error: true
    strategy:

      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    outputs:
      output_grab3: ${{ steps.grab3_outcome.outputs.grab3_outcome}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: NpmInstall
        run: npm install

      - name: Grab
        continue-on-error: true
        id: grab3
        run: |
          npm run grab3
          scale=$(sed -n '$=' ./guide/o2tv.cz_cz.guide.xml)
          echo $scale
          if [[ "$scale" -ge "20" ]]
          then
          echo "++++"
          else
          echo "-----"
          exit 1
          fi

      - name: outcome
        id: grab3_outcome
        shell: bash
        run: |
         echo ${{ github.event_name }}
         echo ${{ steps.grab3.outcome }}
         echo "grab3_outcome=${{ steps.grab3.outcome }}" >> $GITHUB_OUTPUT


      - name: Deploy
        if: ${{ github.event_name == 'workflow_dispatch' }} || ${{ github.event_name == 'schedule' }}
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git config pull.rebase true
          echo ${{ steps.grab3.outcome }}
          git add ./guide/o2tv.cz_cz.guide.xml
          git commit -m "epg-grabber - ${{ steps.grab3.outcome }}"
          git pull
          git push -f
