
name: imdb
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 3 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./imdb   
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: chmod
        run: chmod +x ./imdb.sh
        shell: bash
            
      - name: install apt
        run: sudo apt-get update && sudo apt-get install -y sed && sudo apt-get install -y gawk && sudo apt-get install -y curl
        shell: bash
      - name: run sh
        run: bash ./imdb.sh 
        shell: bash
      

      - name: timestamp
        run: |
          date >> ./timestamp
          stamp=$(date -r ./timestamp)
          echo $stamp
          cd ${{ github.workspace }} 
          sed -i "11s/.*/$stamp | imdb/" ./README.md       
        shell: bash 

      - name: tree 
        run: |
         echo ***./***
         tree -h ./        

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ${{ github.workspace }}/README.md               
          git add ./data/{imdb.csv} 
          git commit -m "imdb"
          git push