
name: namedays
on:
  workflow_dispatch:

jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./namedays
    env:
      SCRAPER: ${{ secrets.SCRAPER }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: sk_SK.utf8
        run: |
          sudo locale-gen sk_SK.utf8
          sudo update-locale LANG=sk_SK.utf8

      - name: chmod
        run: |
          chmod +x ./cal.sh
          chmod +x ./reduce.sh
        shell: bash

      - name: timestamp
        run: |
          date >> ./timestamp
          stamp=$(date -r ./timestamp)
          echo $stamp
          cd ${{ github.workspace }}
          sed -i "10s/.*/$stamp | namedays/" ./README.md
        shell: bash

      - name: tree
        run: |
          echo ***./***
          tree -h ./

      - uses: actions/upload-artifact@v3
        with:
          name: bak
          path: |
            ./namedays/*.*

      - uses: actions/download-artifact@v4
        with:
          path: ./

      - name: run sh
        run: bash ./cal.sh
        shell: bash

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ${{ github.workspace }}/README.md
          git add ./{names_days_min.json,names_days.json}
          git commit -m "namedays"
          git push
