name: Playwright
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        test-group: [ chromium ] # chromium,firefox,webkit
    defaults:
      run:
        working-directory: ./playwright

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Install dependencies
      run: npm install --save
    - name: Install Playwright Browsers
      run: |
       npx playwright install --with-deps ${{ matrix.test-group }}
       npx playwright install --help

    - name: Run Playwright tests
      run: |
       tree -h ${{ github.workspace }}/playwright/tests/
       npx playwright test ${{ github.workspace }}/playwright/tests/solocoo.spec.js --project ${{ matrix.test-group }}
       tree -h ${{ github.workspace }}/playwright/test-results/


    - name: env
      run: |
       echo "$token_CZ"
       echo "${{ env.token_CZ }}"
       echo "$(echo ${{ env.token_CZ}})"
       echo ----------------------------------
       chmod +x ${{ github.workspace }}/epg-grabber/scripts/solocoo_sk_list_curl.sh
       ${{ github.workspace }}/epg-grabber/scripts/solocoo_sk_list_curl.sh
       echo "{path}"
       echo ----------------------------------
       tree -h ${{ github.workspace }}/playwright/test-results/

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-${{ matrix.test-group }}
        path: |
          ${{ github.workspace }}/playwright/playwright-report/
          ${{ github.workspace }}/playwright/test-results/*.*
        retention-days: 30
