name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        test-group: [ chromium ] # chromium,firefox,webkit
    defaults:
      run:
        working-directory: ./playwright

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 'latest'
    - name: Install dependencies
      run: npm install --save
    - name: Install Playwright Browsers
      run: |
       npx playwright install --with-deps ${{ matrix.test-group }}
       npx playwright install --help

    - name: Run Playwright tests
      run: |
       tree -h ${{ github.workspace }}/playwright/tests/
       npx playwright test ${{ github.workspace }}/playwright/tests/solocoo.spec.js --project ${{ matrix.test-group }}
       tree -h ${{ github.workspace }}/playwright/test-results/


    - name: env
      run: |
       echo "$token_CZ"
       echo "${{ env.token_CZ }}"
       echo "$(echo ${{ env.token_CZ }})"
       curl -X GET \
       --no-progress-meter \
       --connect-timeout 10 \
       --max-time 10 \
       --url 'https://tvapi.solocoo.tv/v1/bouquet' \
       -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0' \
       -H 'Accept: application/json, text/plain, */*' \
       -H 'Accept-Language: sk,en-US;q=0.5' \
       -H 'Accept-Encoding: gzip, deflate, br' \
       -H "Authorization: Bearer ${{ env.token_CZ }}" \
       -H 'Origin: https://livetv.skylink.sk' \
       -H 'DNT: 1' \
       -H 'Sec-GPC: 1' \
       -H 'Connection: keep-alive' \
       -H 'Referer: https://livetv.skylink.sk/' \
       -H 'Sec-Fetch-Dest: empty' \
       -H 'Sec-Fetch-Mode: cors' \
       -H 'Sec-Fetch-Site: cross-site' \
       -H 'TE: trailers' \
       | jq -r '.channels[] | ["skylink_sk-\(.assetInfo.params.lcn)", .assetInfo.id, .assetInfo.title, .assetInfo.params.lcn, .assetInfo.images[0].url]'

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-${{ matrix.test-group }}
        path: |
          ${{ github.workspace }}/playwright/playwright-report/
          ${{ github.workspace }}/playwright/test-results/*.*
        retention-days: 30
