name: Playwright Tests
on:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playwright


    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install
    - name: Install Playwright Browsers
      run: |
       npx playwright install --with-deps firefox
       npx playwright install --help

    - name: Run Playwright tests
      run: |
       tree -h ${{ github.workspace }}/playwright/tests/
       npx playwright test ${{ github.workspace }}/playwright/tests/firebaseapp.spec.js --project firefox
       tree -h ${{ github.workspace }}/playwright/test-results/


    - name: env
      run: |
       echo "$theme"
       echo "${{ env.theme }}"
       echo "$(echo ${{ env.theme}})"

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright
        path: |
          ${{ github.workspace }}/playwright/playwright-report/
          ${{ github.workspace }}/playwright/test-results/*.*
        retention-days: 30
