jobs:
workflow_dispatch:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x','pypy-3.7' ]
    name: Python ${{ matrix.python-version }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
 
      - name: 22
       run: pip install csvkit
     - name: csvjson
       run: csvjson -i 4 -k 'asn' clear.csv >> ff.json



      

        

