name: Test code and embed into README

on:
  push:
    branches:
      - main
jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v2
       
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
          python-version: 3.7


     - name: Markdown Embed Code From File
       uses: tokusumi/markdown-embed-code@v1.0.0
       with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "auto commit for embedding"
          no_change: "No change on Readme."
          silent: false
