name: Test code and embed into README

on:
  pull_request:
    branches:
      - main
jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
      - name: embedding readme
        uses: tokusumi/markdown-embed-code@v1.0.0
        with:
          markdown: "README.md"
          token: ${{ secrets.GITHUB_TOKEN }}
          message: "auto commit for embedding"
          no_change: "No change on Readme."
          silent: false
        
