name: Test code and embed into README

on:
  push:
    branches:
      - main
jobs:
  readme-test:
    runs-on: ubuntu-latest
    steps:
     - name: Markdown Embed Code From File
       uses: tokusumi/markdown-embed-code@v1.0.0
