
name: update script
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:
  schedule:
  - cron: '2 1 2 * *'
jobs:
  grab_channels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: chmod
        run: |
         sudo apt-get install xq
         echo -e "\033[31;1m Update chanells. \033[0m"
         chmod +x ./scripts/horizon_tv_list_curl.sh
         bash ./scripts/horizon_tv_list_curl.sh
         chmod +x ./scripts/o2_tv_list_curl.sh
         bash ./scripts/o2_tv_list_curl.sh
         chmod +x ./scripts/skylink_balicky.sh
         bash ./scripts/skylink_balicky.sh
         chmod +x ./scripts/programandroid_list_xq.sh
         bash ./scripts/programandroid_list_xq.sh

        shell: bash

      - name: update-codes
        run: |
         npm install
         npm run update-codes

      - name: tree
        run: |
         echo ***./***
         tree -h ./sites/

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ./csv/*.csv
          git add ./sites/*.xml
          git commit -m "epg-grabber-update-codes"
          git push