
name: update script
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 4 * *'
jobs:
  grab_channels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: chmod
        run: |
         chmod +x ./scripts/list_curl.sh
         bash ./scripts/list_curl.sh
        shell: bash

      - name: tree
        run: |
         echo ***./***
         tree -h ./sites/

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ./sites/*.csv
          git add ./sites/*.xml
          git commit -m "epg-grabber-update-codes"
          git push