
name: update script
run-name: ${{ github.workflow }} ✅ ${{ github.event_name}}
on:
  workflow_call:
  workflow_dispatch:

jobs:
  grab_channels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 2
    defaults:
      run:
        working-directory: ./epg-grabber
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: localle
        uses: milankomaj/shell-x@v0.2
        with:
          shell: bash
          locale: sk_SK.utf8
          timezone: Europe/Bratislava

      - name: xq
        run: |
          echo -e "\033[31;1m Xq Version download Latest version\033[0m"
          XQtool=$(curl -L -s -H 'Accept: application/json' https://github.com/sibprogrammer/xq/releases/latest)
          VersionXQtool=$(echo $XQtool | sed -e 's/.*"tag_name":"\([^"]*\)".*/\1/')
          echo VersionXQtool = $VersionXQtool
          echo $VersionXQtool
          short=$(echo $VersionXQtool | cut -c 2-)
          echo $short
          URL=$(curl -s -L -o xq_$(echo $short)_linux_amd64.tar.gz https://github.com/sibprogrammer/xq/releases/download/$(echo $VersionXQtool)/xq_$(echo $short)_linux_amd64.tar.gz)
          tar -xvzf xq_$(echo $short)_linux_amd64.tar.gz xq
        shell: bash

      - name: chmod
        run: |
          echo -e "\033[31;1m Update chanells. \033[0m"
          chmod +x ./scripts/horizon_tv_list_curl.sh
          ./scripts/horizon_tv_list_curl.sh
          chmod +x ./scripts/o2_tv_list_curl.sh
          ./scripts/o2_tv_list_curl.sh
          chmod +x ./scripts/skylink_balicky.sh
          ./scripts/skylink_balicky.sh
          chmod +x ./scripts/programandroid_list_xq.sh
          ./scripts/programandroid_list_xq.sh
           chmod +x ./scripts/mujtvprogram_list_xq.sh
          ./scripts/mujtvprogram_list_xq.sh
        shell: bash

      - name: update-codes
        run: |
          npm install
          npm run update-codes

      - name: tree
        run: |
          echo ***./sites/***
          tree -h ./sites/
          echo ***./channels/***
          tree -h ./channels/

      - name: deploy
        run: |
          git config --global user.email ${{ secrets.EMAIL }}
          git config --global user.name ${{ secrets.NAME }}
          git pull
          git add ./csv/*.csv
          git add ./channels/*.xml
          git ls-tree -r main --name-only
          git commit -m "epg-grabber-update-codes" || echo
          git push
