name: process
on:
  workflow_dispatch:
jobs:
  grab:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: npm install
      - name: CD
        run: cd script
      - name: Run Npm gh
        run: npm run gh       

