name: TEST
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: tt
      run: ./test.sh
      
      


   
