name: TEST
on:

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: tt
      git config --global user.email "milankomaj+Github@gmail.com"
      git config --global user.name " milankomaj"
      run: ./test.sh
      
      


   
