name: run-script
on: push
workflow_dispatch:
jobs:
run:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v1
- name: script
run:|
    
    chmod +x "${GITHUB_WORKSPACE}/.github/test.sh"

    
    "${GITHUB_WORKSPACE}/.github/test.sh"