name: TEST
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - uses: actions/checkout@v1
    - name: Get
      shell: bash

  run: |
      chmod +x "${GITHUB_WORKSPACE}/.github/test.sh"
      ${GITHUB_WORKSPACE}/.github/test.sh


   
