name: TEST
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest


- name: Get
- uses: actions/checkout@v1
  run: bash ./test.sh


   
