name: TEST
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
 steps:  
    - uses: actions/checkout@v1
    - name: Get
    uses: actions/checkout@v1
    - name: Run
    run: |
    bash ${GITHUB_WORKSPACE}/.github/test.sh


   
