name: process
on:
  workflow_dispatch:
  schedule:
  - cron: '0 6 3 * *'
jobs:
  grab:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    continue-on-error: true
    strategy:
      fail-fast: false
      max-parallel: 2
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: chmod
        run: chmod +x ./asn.sh
        shell: bash
      - name: echo timestamp
        run: date >> ./data/timestamp
        shell: bash   
      - name: timestamp
        run: |
           stamp=$(date -r ./data/timestamp)
           echo $stamp
           sed -i "2s/.*/$stamp/" ./README.md 
           zone=$(TZ='Europe/Bratislava' date -r ./data/timestamp)
           echo $zone
           sed -i "3s/.*/$zone/" ./README.md
      - name: install
        run: sudo apt-get update && sudo apt-get install -y sed && sudo apt-get install -y gawk && sudo apt-get install -y curl
        shell: bash
      - name: run sh
        run: bash ./asn.sh 
        shell: bash
      - name: Install Dependencies
        run: npm install       
      - name: Run Npm gh-merge
        run: npm run gh-merge
      - name: Run Npm gh-asn
        run: npm run gh-asn
      - name: Run Npm gh-od-do
        run: npm run gh-od-do
      - name: Deploy
        run: |         
         git config --global user.email ${{ secrets.EMAIL }}
         git config --global user.name ${{ secrets.NAME }}
         git add -A
         git commit -m "update data"
         git push --force   

   

    


         
          
        
        
