name: MasterDeployCI
on:
  workflow_dispatch:
  push:
    branches:
      - out
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Zip Folder
      run: zip -r release.zip . -x ".git/*" ".github/*"
    - name: Release to Github
      run: echo "Release"
